apiVersion: v1
kind: Service
metadata:
  name: "{{ include \"rag-etl.fullname\" . }}"
  labels:
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/name": "{{ .Chart.Name }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/version": "{{ .Chart.AppVersion }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
spec:
  type: "{{ .Values.service.type | default \"ClusterIP\" }}"
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    "app.kubernetes.io/name": "{{ .Chart.Name }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
