"""

Revision ID: 79acfe87e810
Revises: a6c4dbc142b3
Create Date: 2025-09-13 13:26:04.963529

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "79acfe87e810"
down_revision: Union[str, None] = "a6c4dbc142b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE documenttype RENAME VALUE 'PRESS_ANNOUNCEMENT' TO 'GENERAL'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE documenttype RENAME VALUE 'GENERAL' TO 'PRESS_ANNOUNCEMENT'")
    # ### end Alembic commands ###
