"""

Revision ID: a6c4dbc142b3
Revises: 20250912_add_utterance
Create Date: 2025-09-13 00:04:32.420088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6c4dbc142b3"
down_revision: Union[str, None] = "20250912_add_utterance"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("progress", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "progress")
    # ### end Alembic commands ###
